import type { Metadata } from 'next';
import { Lexend_Deca, Hind } from 'next/font/google';
import './globals.css';
import Header from '@/components/header/Header';
import MouseFollower from '@/components/MouseFollower';
import Footer from '@/components/Footer';

const lexendDeca = Lexend_Deca({
  variable: '--font-lexend-deca',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  fallback: [
    'ui-sans-serif',
    'system-ui',
    '-apple-system',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'Noto Sans',
    'sans-serif',
    'Apple Color Emoji',
    'Segoe UI Emoji',
    'Segoe UI Symbol',
    'Noto Color Emoji',
  ],
});

const hind = Hind({
  variable: '--font-hind',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  fallback: [
    'ui-sans-serif',
    'system-ui',
    '-apple-system',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Roboto',
    'Helvetica Neue',
    'Arial',
    'Noto Sans',
    'sans-serif',
    'Apple Color Emoji',
    'Segoe UI Emoji',
    'Segoe UI Symbol',
    'Noto Color Emoji',
  ],
});

export const metadata: Metadata = {
  title: 'TechSprout School',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${lexendDeca.variable} ${hind.variable} `}>
      <body className='font-hind bg-[#F4F7FB] antialiased'>
        <>
          <Header />
          {children}
          <Footer />

          <MouseFollower />
        </>
      </body>
    </html>
  );
}
