import {
  User,
  Course,
  Enrolment,
  Review,
  Blog,
  Cart,
  Order,
  Question,
  Instructor,
  Subscriber,
} from './mockDataTypes';
import courseImg1 from '@/assets/img/courses/courses03.jpg';
import courseImg2 from '@/assets/img/courses/courses05.jpg';
import courseImg3 from '@/assets/img/courses/courses06.jpg';
import courseImg4 from '@/assets/img/courses/courses10.jpg';
import instructor1 from '@/assets/img/instructors/instructor01.png';
import instructor2 from '@/assets/img/instructors/instructor02.png';
import instructor3 from '@/assets/img/instructors/instructor03.png';
import instructor4 from '@/assets/img/instructors/instructor04.png';
import blogImg1 from '@/assets/img/blogs/blog_standard01.jpg';
import blogImg2 from '@/assets/img/blogs/blog_standard02.jpg';
import blogImg3 from '@/assets/img/blogs/blog_standard03.jpg';

// Users
export const users: User[] = [
  {
    _id: 'u1',
    name: 'Alice Johnson',
    username: 'alicej',
    email: 'alice@example.com',
    phone: '01710000001',
    password: 'hashed123',
    occupation: 'Designer',
    bio: 'UX/UI Designer with 5 years experience',
    socialLinks: ['https://linkedin.com/alicej'],
    image: instructor1.src,
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: ['c2'],
  },
  {
    _id: 'u2',
    name: 'Bob Smith',
    username: 'bobsmith',
    email: 'bob@example.com',
    phone: '01710000002',
    password: 'hashed456',
    occupation: 'Backend Developer',
    bio: 'Node.js developer',
    socialLinks: ['https://github.com/bobsmith'],
    image: instructor2.src,
    role: 'instructor',
    registeredAt: new Date().toISOString(),
    wishlist: ['c1'],
  },
  {
    _id: 'u3',
    name: 'Cathy Lee',
    username: 'cathyl',
    email: 'cathy@example.com',
    phone: '01710000003',
    password: 'hashed789',
    occupation: 'Data Analyst',
    bio: 'Works with data at a fintech company',
    socialLinks: ['https://twitter.com/cathyl'],
    image: instructor3.src,
    role: 'admin',
    registeredAt: new Date().toISOString(),
    wishlist: ['c4'],
  },
  {
    _id: 'u4',
    name: 'David Kim',
    username: 'davidk',
    email: 'david@example.com',
    phone: '01710000004',
    password: 'hashed101',
    occupation: 'Product Manager',
    bio: 'Manages software projects',
    socialLinks: [],
    image: instructor4.src,
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: [],
  },
  {
    _id: 'u5',
    name: 'Eva Green',
    username: 'evagreen',
    email: 'eva@example.com',
    phone: '01710000005',
    password: 'hashed102',
    occupation: 'Full Stack Developer',
    bio: 'Freelancer',
    socialLinks: ['https://github.com/evagreen'],
    image: instructor1.src,
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: ['c5'],
  },
  {
    _id: 'u6',
    name: 'Frank Miller',
    username: 'frankm',
    email: 'frank@example.com',
    phone: '01710000006',
    password: 'hashed103',
    occupation: 'DevOps Engineer',
    bio: 'Cloud infrastructure specialist',
    socialLinks: ['https://linkedin.com/frankm'],
    image: instructor2.src,
    role: 'instructor',
    registeredAt: new Date().toISOString(),
    wishlist: ['c6', 'c7'],
  },
  {
    _id: 'u7',
    name: 'Grace Wilson',
    username: 'gracew',
    email: 'grace@example.com',
    phone: '01710000007',
    password: 'hashed104',
    occupation: 'Marketing Manager',
    bio: 'Digital marketing enthusiast',
    socialLinks: ['https://twitter.com/gracew', 'https://instagram.com/gracew'],
    image: instructor3.src,
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: ['c8'],
  },
  {
    _id: 'u8',
    name: 'Henry Brown',
    username: 'henryb',
    email: 'henry@example.com',
    phone: '01710000008',
    password: 'hashed105',
    occupation: 'Mobile Developer',
    bio: 'React Native and Flutter developer',
    socialLinks: ['https://github.com/henryb'],
    image: instructor4.src,
    role: 'instructor',
    registeredAt: new Date().toISOString(),
    wishlist: ['c9'],
  },
  {
    _id: 'u9',
    name: 'Ivy Chen',
    username: 'ivyc',
    email: 'ivy@example.com',
    phone: '01710000009',
    password: 'hashed106',
    occupation: 'QA Engineer',
    bio: 'Automation testing specialist',
    socialLinks: ['https://linkedin.com/ivyc'],
    image: instructor1.src,
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: ['c10'],
  },
  {
    _id: 'u10',
    name: 'Jack Davis',
    username: 'jackd',
    email: 'jack@example.com',
    phone: '01710000010',
    password: 'hashed107',
    occupation: 'AI Engineer',
    bio: 'Machine learning and AI researcher',
    socialLinks: ['https://github.com/jackd', 'https://medium.com/@jackd'],
    image: instructor2.src,
    role: 'instructor',
    registeredAt: new Date().toISOString(),
    wishlist: ['c1', 'c3'],
  },
];

// Courses
export const courses: Course[] = [
  {
    _id: 'c1',
    title: 'Intro to JavaScript',
    category: 'Web Development',
    duration: '10 hours',
    price: 29.99,
    isFree: false,
    thumbnail: courseImg1.src,
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: [
      'https://www.w3schools.com/html/mov_bbb.mp4',
      'https://www.w3schools.com/html/movie.mp4',
    ],
    featured: true,
    instructor: 'u2',
    reviews: ['r1', 'r11', 'r21'],
    enrolments: ['e1', 'e11', 'e21'],
    description:
      "Dive into the world of web development with our 'Intro to JavaScript' course. This comprehensive program is designed for absolute beginners, providing a solid foundation in the core concepts of JavaScript, the language that powers dynamic and interactive websites. You'll start with the basics, including variables, data types, and operators, before moving on to more complex topics like control structures, functions, and arrays. Our hands-on approach ensures you'll be writing code from day one, with practical exercises and projects that reinforce your learning. We'll also cover essential concepts like the Document Object Model (DOM), which allows you to manipulate web page content and create engaging user experiences. By the end of this course, you'll have the skills to build simple, yet powerful, web applications and be well-prepared to tackle more advanced JavaScript frameworks. This course is your first step towards becoming a proficient web developer, equipping you with the fundamental knowledge to bring your ideas to life on the web.",
    audience: [
      'Aspiring web developers who are new to programming.',
      'Students and individuals looking to start a career in technology.',
      'Designers who want to add interactive elements to their websites.',
      'Hobbyists interested in learning how websites work under the hood.',
    ],
    requirements: [
      'A computer with a modern web browser.',
      'An internet connection.',
      'A code editor (like VS Code, free).',
    ],
    resources: [
      'Interactive coding challenges and quizzes.',
      'Downloadable course materials and code examples.',
      'Access to a private online community for support.',
      'Instructor-led Q&A sessions.',
    ],
    keyLearningPoints: [
      'Understanding the fundamental syntax and concepts of JavaScript.',
      'Manipulating the Document Object Model (DOM) to create dynamic content.',
      'Working with variables, data types, and functions.',
      'Implementing control flow and handling errors in your code.',
      'Building a simple web application from start to finish.',
    ],
  },
  {
    _id: 'c2',
    title: 'Advanced CSS',
    category: 'Web Development',
    duration: '15 hours',
    price: 39.99,
    isFree: false,
    thumbnail: courseImg2.src,
    demoVideo: 'https://www.w3schools.com/html/movie.mp4',
    lessons: ['https://www.w3schools.com/html/movie.mp4'],
    featured: false,
    instructor: 'u2',
    reviews: ['r2', 'r12', 'r22'],
    enrolments: ['e2', 'e12', 'e22'],
    description:
      "Take your web design skills to the next level with our 'Advanced CSS' course. This program is for developers who already have a basic understanding of CSS and are ready to master modern techniques and best practices. We'll explore advanced layout systems like CSS Grid and Flexbox in detail, teaching you how to create complex, responsive, and maintainable designs with ease. The course covers a wide range of topics, including advanced selectors, custom properties (CSS variables), and preprocessors like Sass. You'll learn how to create stunning animations and transitions, giving your websites a polished, professional feel. We'll also dive into responsive design principles, ensuring your sites look great on any device, from desktops to mobile phones. With practical projects that challenge you to apply what you've learned, you'll gain the confidence to build visually impressive and highly functional user interfaces. This course is essential for any front-end developer looking to stand out in the competitive world of web design.",
    audience: [
      'Front-end developers with a basic understanding of CSS.',
      'Web designers who want to build more complex and responsive layouts.',
      'Individuals looking to improve their UI/UX skills.',
      'Professionals who want to master modern CSS techniques like Flexbox and Grid.',
    ],
    requirements: [
      'A computer with a modern web browser.',
      'An internet connection.',
      'A text editor.',
      'Basic knowledge of HTML and CSS.',
    ],
    resources: [
      'Project files and starter code for hands-on exercises.',
      'Reference guides for CSS properties and selectors.',
      'Examples of advanced CSS animations and transitions.',
      'Video tutorials and code-along sessions.',
    ],
    keyLearningPoints: [
      'Mastering CSS Flexbox and Grid for powerful layouts.',
      'Creating responsive designs with media queries and mobile-first approaches.',
      'Using CSS custom properties (variables) for scalable design systems.',
      'Implementing complex animations and transitions for improved user experience.',
      'Writing cleaner and more maintainable CSS code with preprocessors like Sass.',
    ],
  },
  {
    _id: 'c3',
    title: 'React Basics',
    category: 'Web Development',
    duration: '8 hours',
    price: 0,
    isFree: true,
    thumbnail: courseImg3.src,
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: ['https://www.w3schools.com/html/mov_bbb.mp4'],
    featured: true,
    instructor: 'u5',
    reviews: ['r3', 'r13', 'r23'],
    enrolments: ['e3', 'e13', 'e23'],
    description:
      "Unlock the power of modern front-end development with our free 'React Basics' course. This introductory program is perfect for developers who are new to the React ecosystem and want to learn how to build single-page applications efficiently. We'll guide you through the fundamental concepts of React, starting with components, JSX, and props. You'll learn how to manage state and handle user interactions, which are crucial for creating dynamic web interfaces. The course provides a hands-on learning experience with practical examples and small projects that solidify your understanding. We'll cover the virtual DOM, component lifecycle, and how to use popular hooks like `useState` and `useEffect`. By the end of this course, you'll be able to create a functional and interactive React application from scratch. This free offering is an excellent opportunity to gain a valuable skill that is highly sought after by employers worldwide, setting you on the path to a rewarding career in web development.",
    audience: [
      'Developers with a basic understanding of HTML, CSS, and JavaScript.',
      'Students and professionals aiming for a career in front-end development.',
      'Anyone interested in learning one of the most popular JavaScript libraries.',
    ],
    requirements: [
      'A computer with Node.js and a code editor installed.',
      'An internet connection.',
      'Familiarity with JavaScript fundamentals.',
    ],
    resources: [
      'Interactive coding exercises within a React environment.',
      'Templates and boilerplate code for your first React projects.',
      'Community forum for questions and peer support.',
      'Detailed explanations of core React concepts.',
    ],
    keyLearningPoints: [
      'Understanding the component-based architecture of React.',
      'Working with JSX to write declarative UI code.',
      'Managing component state and props for dynamic applications.',
      'Using React Hooks like `useState` and `useEffect` effectively.',
      'Building a complete, interactive React application from the ground up.',
    ],
  },
  {
    _id: 'c4',
    title: 'Figma for UI/UX Design',
    category: 'Graphics Design',
    duration: '20 hours',
    price: 59.99,
    isFree: false,
    thumbnail: courseImg4.src,
    demoVideo: 'https://www.w3schools.com/html/movie.mp4',
    lessons: ['https://www.w3schools.com/html/movie.mp4'],
    featured: false,
    instructor: 'u3',
    reviews: ['r4', 'r14', 'r24'],
    enrolments: ['e4', 'e14', 'e24'],
    description:
      "Become a master of modern design with our 'Figma for UI/UX Design' course. Figma is the industry-standard tool for collaborative interface design, and this course will teach you everything you need to know to create stunning and functional user interfaces and user experiences. We'll start with the fundamentals of the Figma interface, including frames, shapes, and text tools. You'll learn how to create and manage design systems, using components, variants, and auto-layout to build scalable and consistent designs. The course covers key UI/UX principles, such as typography, color theory, and wireframing, to help you create user-centered designs. We'll also explore prototyping and collaboration features, allowing you to create interactive prototypes and work seamlessly with other designers and developers. With hands-on projects and real-world case studies, you'll build a professional portfolio piece that demonstrates your ability to design beautiful and effective digital products. This course is perfect for aspiring UI/UX designers, graphic designers, and front-end developers who want to take control of their design workflow.",
    audience: [
      'Aspiring UI/UX designers and graphic designers.',
      'Product managers and developers who want to understand the design process.',
      'Entrepreneurs and business owners creating their own digital products.',
      'Individuals who want to master Figma, the industry-standard design tool.',
    ],
    requirements: [
      'A computer with a modern web browser.',
      'An internet connection.',
      'A free Figma account.',
    ],
    resources: [
      'Practical projects to build a professional portfolio.',
      'Templates and design assets to get started quickly.',
      'Access to a private community for design feedback.',
      'Case studies of real-world UI/UX projects.',
    ],
    keyLearningPoints: [
      'Mastering the Figma interface and its essential tools.',
      'Building scalable design systems with components and variants.',
      'Applying UI/UX principles to create user-centered designs.',
      'Creating interactive prototypes to test user flows.',
      'Collaborating effectively with teams on a single design file.',
    ],
  },
  {
    _id: 'c5',
    title: 'WordPress Web Design',
    category: 'Web Design',
    duration: '12 hours',
    price: 19.99,
    isFree: false,
    thumbnail: courseImg1.src,
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: ['https://www.w3schools.com/html/mov_bbb.mp4'],
    featured: true,
    instructor: 'u2',
    reviews: ['r5', 'r15', 'r25'],
    enrolments: ['e5', 'e15', 'e25'],
    description:
      "Launch your career in web design with our practical 'WordPress Web Design' course. WordPress powers over 40% of the internet, making it an essential skill for any web professional. This course is designed for beginners and will walk you through the entire process of building a professional website from scratch without writing a single line of code. You'll learn how to set up WordPress, choose and customize themes, and use powerful plugins to add functionality like e-commerce, contact forms, and SEO. We'll cover the fundamentals of site structure, navigation, and content management, ensuring you can build websites that are both user-friendly and easy to maintain. By the end of the course, you'll be able to create a fully functional, responsive, and visually appealing website for a business or personal portfolio. This course provides a fast and efficient path to becoming a freelance web designer or starting your own digital agency, giving you the skills to meet the high demand for WordPress expertise.",
    audience: [
      'Aspiring freelance web designers.',
      'Small business owners who want to build their own website.',
      'Marketers who need to manage and update WordPress sites.',
      'Individuals with no coding experience who want to create websites.',
    ],
    requirements: [
      'A computer with a modern web browser.',
      'An internet connection.',
      'A domain name and hosting (optional, but recommended).',
    ],
    resources: [
      'Step-by-step video tutorials on setting up WordPress.',
      'Recommendations for free and premium themes and plugins.',
      'Checklists for launching a professional website.',
      'Templates for business and portfolio websites.',
    ],
    keyLearningPoints: [
      'Setting up and configuring a new WordPress installation.',
      'Customizing themes and creating professional-looking pages.',
      'Using plugins to add essential functionality like contact forms and SEO.',
      'Building a responsive and user-friendly website without code.',
      'Understanding the fundamentals of content management in WordPress.',
    ],
  },
  {
    _id: 'c6',
    title: 'Advanced SEO Techniques',
    category: 'SEO',
    duration: '25 hours',
    price: 34.99,
    isFree: false,
    thumbnail: courseImg2.src,
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: [
      'https://www.w3schools.com/html/mov_bbb.mp4',
      'https://www.w3schools.com/html/movie.mp4',
    ],
    featured: true,
    instructor: 'u6',
    reviews: ['r6', 'r16', 'r26'],
    enrolments: ['e6', 'e16', 'e26'],
    description:
      "Master the art and science of getting your website to the top of search engine results with our 'Advanced SEO Techniques' course. This program is for digital marketers, website owners, and developers who have a basic understanding of SEO and want to learn advanced strategies to dominate their niche. We'll go beyond the basics of keywords and on-page optimization to explore technical SEO, including site architecture, structured data, and Core Web Vitals. You'll learn how to perform comprehensive competitor analysis, build a powerful link-building strategy, and master the art of content marketing for organic growth. We'll also cover the latest algorithm updates and how to adapt your strategy to stay ahead of the curve. The course includes hands-on projects where you'll audit a live website and develop a full-scale SEO plan, giving you the practical experience needed to deliver real results. By the end of this course, you'll have the expertise to drive significant organic traffic and increase your website's visibility and authority.",
    audience: [
      'Digital marketers and SEO professionals with foundational knowledge.',
      'Website owners and bloggers who want to increase organic traffic.',
      'Developers who need to implement technical SEO best practices.',
      'Marketing managers responsible for a company’s online visibility.',
    ],
    requirements: [
      'A computer with a modern web browser.',
      'An internet connection.',
      'A basic understanding of SEO principles.',
    ],
    resources: [
      'Tools and templates for SEO audits and competitor analysis.',
      'Case studies of successful SEO campaigns.',
      'Downloadable guides on technical SEO and link-building.',
      'Video tutorials on using popular SEO tools like Semrush and Ahrefs.',
    ],
    keyLearningPoints: [
      'Performing advanced keyword research and competitor analysis.',
      'Mastering technical SEO for site architecture and performance.',
      'Developing a comprehensive and effective link-building strategy.',
      'Creating a content marketing plan that drives organic traffic.',
      'Staying up-to-date with the latest search engine algorithm updates.',
    ],
  },
  {
    _id: 'c7',
    title: 'Digital Marketing Essentials',
    category: 'Digital Marketing',
    duration: '18 hours',
    price: 49.99,
    isFree: false,
    thumbnail: courseImg1.src,
    demoVideo: 'https://www.w3schools.com/html/movie.mp4',
    lessons: ['https://www.w3schools.com/html/movie.mp4'],
    featured: false,
    instructor: 'u7',
    reviews: ['r7', 'r17', 'r27'],
    enrolments: ['e7', 'e17', 'e27'],
    description:
      "Lay the groundwork for a successful career in digital marketing with our 'Digital Marketing Essentials' course. This comprehensive program is designed for beginners and business owners who want to understand the key components of a successful online presence. You'll learn the fundamentals of search engine optimization (SEO), social media marketing, email marketing, and content strategy. We'll cover how to create a marketing plan, identify your target audience, and set measurable goals. The course provides a practical overview of popular marketing tools and platforms, including Google Analytics, Facebook Ads, and email service providers. Through hands-on exercises and case studies, you'll gain the skills to build and execute a cohesive digital marketing strategy that drives traffic, generates leads, and increases conversions. By the end of this course, you'll have the confidence to manage your own marketing efforts or work effectively as part of a marketing team, equipped with the essential knowledge to navigate the digital landscape.",
    audience: [
      'Marketing students and professionals new to the digital landscape.',
      'Small business owners and entrepreneurs.',
      'Aspiring digital marketers and social media managers.',
      'Individuals who want to understand the core pillars of online marketing.',
    ],
    requirements: [
      'A computer with a modern web browser.',
      'An internet connection.',
      'A willingness to learn and apply new marketing concepts.',
    ],
    resources: [
      'Guides and templates for creating a digital marketing plan.',
      'Case studies of effective marketing campaigns.',
      'Walkthroughs of Google Analytics and social media advertising platforms.',
      'Interactive quizzes to test your knowledge of key concepts.',
    ],
    keyLearningPoints: [
      'Developing a complete digital marketing strategy from scratch.',
      'Understanding the fundamentals of SEO, content, and email marketing.',
      'Creating and executing a social media marketing plan.',
      'Using analytics to measure campaign performance and ROI.',
      'Identifying your target audience and creating a customer-centric strategy.',
    ],
  },
  {
    _id: 'c8',
    title: 'Adobe Illustrator for Beginners',
    category: 'Graphics Design',
    duration: '9 hours',
    price: 0,
    isFree: true,
    thumbnail: courseImg2.src,
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: ['https://www.w3schools.com/html/mov_bbb.mp4'],
    featured: true,
    instructor: 'u8',
    reviews: ['r8', 'r18', 'r28'],
    enrolments: ['e8', 'e18', 'e28'],
    description:
      "Unleash your creativity with our free 'Adobe Illustrator for Beginners' course. This introductory program is the perfect starting point for anyone who wants to learn vector graphics design. You'll master the essential tools and techniques of Adobe Illustrator, the industry-standard software for creating logos, icons, illustrations, and more. We'll cover the basics of the interface, from creating new documents to working with artboards and layers. The course provides a step-by-step guide to using drawing tools, manipulating shapes, and working with color and typography. Through simple, guided projects, you'll learn how to create your own vector artwork, ready for use on websites, print materials, and other digital platforms. By the end of this free course, you'll have a solid understanding of vector design principles and the practical skills to start your journey as a graphic designer. It’s an excellent opportunity to build a foundational skill set and explore your passion for visual communication.",
    audience: [
      'Absolute beginners to graphic design and Adobe software.',
      'Individuals who want to create logos, icons, and vector art.',
      'Web designers and developers who need to create custom graphics.',
      'Anyone looking for a free, high-quality introduction to vector design.',
    ],
    requirements: [
      'A computer capable of running Adobe Illustrator.',
      'An internet connection.',
      'Adobe Illustrator (free trial or subscription).',
    ],
    resources: [
      'Step-by-step video tutorials and guided projects.',
      'Downloadable Illustrator project files and assets.',
      'Cheat sheets for essential tools and shortcuts.',
      'Community for sharing work and getting feedback.',
    ],
    keyLearningPoints: [
      'Understanding the Adobe Illustrator interface and core concepts.',
      'Using essential drawing tools to create vector shapes and paths.',
      'Working with colors, gradients, and typography for effective design.',
      'Creating a simple logo and other vector illustrations.',
      'Preparing vector graphics for both web and print use.',
    ],
  },
  {
    _id: 'c9',
    title: 'E-commerce SEO Strategies',
    category: 'SEO',
    duration: '14 hours',
    price: 24.99,
    isFree: false,
    thumbnail: courseImg3.src,
    demoVideo: 'https://www.w3schools.com/html/movie.mp4',
    lessons: ['https://www.w3schools.com/html/movie.mp4'],
    featured: false,
    instructor: 'u9',
    reviews: ['r9', 'r19', 'r29'],
    enrolments: ['e9', 'e19', 'e29'],
    description:
      "Boost your online store's visibility and sales with our specialized 'E-commerce SEO Strategies' course. This program is tailored for business owners, marketers, and SEO professionals who want to master the unique challenges of optimizing an e-commerce website for search engines. We'll delve into topics like keyword research for products and categories, optimizing product pages for conversions, and structuring your site for maximum crawlability. You'll learn how to handle common e-commerce SEO issues such as duplicate content, faceted navigation, and a lack of inbound links. We'll also cover advanced strategies like schema markup for product ratings and reviews, and how to leverage blog content to drive targeted traffic to your store. Through practical exercises and real-world examples, you'll be able to create and implement a powerful SEO plan that increases organic traffic and, most importantly, revenue. This course is a game-changer for anyone looking to scale their e-commerce business through sustainable and effective search engine optimization.",
    audience: [
      'E-commerce store owners and managers.',
      'Digital marketers and SEO specialists focused on e-commerce.',
      'Business owners who want to grow their online sales organically.',
      'Freelancers who manage SEO for e-commerce clients.',
    ],
    requirements: [
      'A computer with a modern web browser.',
      'An internet connection.',
      'An existing e-commerce website (or a plan to build one).',
    ],
    resources: [
      'Templates for e-commerce keyword research.',
      'Guides on product page optimization and technical SEO.',
      'Case studies of successful e-commerce SEO campaigns.',
      'Access to a private community for e-commerce discussions.',
    ],
    keyLearningPoints: [
      'Conducting e-commerce-specific keyword research.',
      'Optimizing product and category pages for higher rankings and conversions.',
      'Implementing technical SEO to improve site crawlability and indexation.',
      'Developing a link-building and content strategy for an online store.',
      'Using schema markup to enhance product listings in search results.',
    ],
  },
  {
    _id: 'c10',
    title: 'Social Media Marketing',
    category: 'Digital Marketing',
    duration: '30 hours',
    price: 79.99,
    isFree: false,
    thumbnail: courseImg4.src,
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: [
      'https://www.w3schools.com/html/mov_bbb.mp4',
      'https://www.w3schools.com/html/movie.mp4',
    ],
    featured: true,
    instructor: 'u10',
    reviews: ['r10', 'r20', 'r30'],
    enrolments: ['e10', 'e20', 'e30'],
    description:
      "Harness the power of social media to grow your brand and connect with your audience in our 'Social Media Marketing' course. This comprehensive program is designed for marketers, business owners, and aspiring social media managers who want to build a powerful and effective social media presence. You'll learn how to develop a winning social media strategy, from defining your target audience and choosing the right platforms to creating engaging content and building a content calendar. We'll dive deep into the specific strategies for major platforms like Facebook, Instagram, Twitter, and LinkedIn, covering both organic and paid advertising methods. The course also includes modules on social media analytics, so you can track your performance, measure your ROI, and make data-driven decisions. By the end of this course, you'll have the skills to manage a full-scale social media campaign, build a thriving online community, and drive tangible business results. This is your definitive guide to becoming a social media marketing expert.",
    audience: [
      'Marketers and social media managers.',
      'Business owners and entrepreneurs.',
      'Content creators and influencers.',
      'Anyone interested in building and managing a brand’s social media presence.',
    ],
    requirements: [
      'A computer with a modern web browser.',
      'An internet connection.',
      'Social media accounts (optional, but recommended for practice).',
    ],
    resources: [
      'Templates for social media content calendars and strategies.',
      'Guides on using social media analytics tools.',
      'Case studies of successful social media campaigns.',
      'Video tutorials on creating content for different platforms.',
    ],
    keyLearningPoints: [
      'Developing a strategic social media marketing plan.',
      'Creating engaging and shareable content for various platforms.',
      'Running effective paid advertising campaigns on social media.',
      'Using analytics to measure performance and optimize your strategy.',
      'Building a strong online community and engaging with your audience.',
    ],
  },
];

// Enrolments
export const enrolments: Enrolment[] = [
  { _id: 'e1', user: 'u1', course: 'c1', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e2',
    user: 'u2',
    course: 'c2',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e3', user: 'u3', course: 'c3', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e4',
    user: 'u4',
    course: 'c4',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e5', user: 'u5', course: 'c5', status: 'active', enrolledAt: new Date().toISOString() },
  { _id: 'e6', user: 'u6', course: 'c6', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e7',
    user: 'u7',
    course: 'c7',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e8', user: 'u8', course: 'c8', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e9',
    user: 'u9',
    course: 'c9',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  {
    _id: 'e10',
    user: 'u10',
    course: 'c10',
    status: 'active',
    enrolledAt: new Date().toISOString(),
  },
  // Additional enrollments for multiple per course
  {
    _id: 'e11',
    user: 'u4',
    course: 'c1',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e12', user: 'u5', course: 'c2', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e13',
    user: 'u6',
    course: 'c3',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e14', user: 'u7', course: 'c4', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e15',
    user: 'u8',
    course: 'c5',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e16', user: 'u9', course: 'c6', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e17',
    user: 'u10',
    course: 'c7',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e18', user: 'u1', course: 'c8', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e19',
    user: 'u2',
    course: 'c9',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e20', user: 'u3', course: 'c10', status: 'active', enrolledAt: new Date().toISOString() },
  // Third enrollment for each course
  { _id: 'e21', user: 'u7', course: 'c1', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e22',
    user: 'u8',
    course: 'c2',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e23', user: 'u9', course: 'c3', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e24',
    user: 'u10',
    course: 'c4',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e25', user: 'u1', course: 'c5', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e26',
    user: 'u2',
    course: 'c6',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e27', user: 'u3', course: 'c7', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e28',
    user: 'u4',
    course: 'c8',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e29', user: 'u5', course: 'c9', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e30',
    user: 'u6',
    course: 'c10',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
];

// Reviews
export const reviews: Review[] = [
  {
    _id: 'r1',
    user: 'u1',
    course: 'c1',
    rating: 5,
    comment: 'Loved it!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r2',
    user: 'u2',
    course: 'c2',
    rating: 4,
    comment: 'Great explanations.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r3',
    user: 'u3',
    course: 'c3',
    rating: 3,
    comment: 'Good but basic.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r4',
    user: 'u4',
    course: 'c4',
    rating: 4,
    comment: 'Well structured.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r5',
    user: 'u5',
    course: 'c5',
    rating: 5,
    comment: 'Perfect for beginners!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r6',
    user: 'u6',
    course: 'c6',
    rating: 4,
    comment: 'Docker made easy!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r7',
    user: 'u7',
    course: 'c7',
    rating: 5,
    comment: 'Comprehensive marketing guide.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r8',
    user: 'u8',
    course: 'c8',
    rating: 4,
    comment: 'Great for mobile development.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r9',
    user: 'u9',
    course: 'c9',
    rating: 3,
    comment: 'Solid foundation in testing.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r10',
    user: 'u10',
    course: 'c10',
    rating: 5,
    comment: 'Excellent ML course!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  // Additional reviews for multiple per course
  {
    _id: 'r11',
    user: 'u4',
    course: 'c1',
    rating: 4,
    comment: 'Clear and concise JavaScript tutorial.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r12',
    user: 'u5',
    course: 'c2',
    rating: 5,
    comment: 'CSS animations were amazing!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r13',
    user: 'u6',
    course: 'c3',
    rating: 4,
    comment: 'Good introduction to React.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r14',
    user: 'u7',
    course: 'c4',
    rating: 5,
    comment: 'Beautiful visualizations taught here.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r15',
    user: 'u8',
    course: 'c5',
    rating: 4,
    comment: 'Solid Node.js fundamentals.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r16',
    user: 'u9',
    course: 'c6',
    rating: 5,
    comment: 'Container concepts well explained.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r17',
    user: 'u10',
    course: 'c7',
    rating: 4,
    comment: 'Practical marketing strategies.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r18',
    user: 'u1',
    course: 'c8',
    rating: 5,
    comment: 'Mobile development made simple.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r19',
    user: 'u2',
    course: 'c9',
    rating: 4,
    comment: 'Comprehensive testing coverage.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r20',
    user: 'u3',
    course: 'c10',
    rating: 5,
    comment: "Best ML course I've taken!",
    featured: true,
    createdAt: new Date().toISOString(),
  },
  // Third review for each course
  {
    _id: 'r21',
    user: 'u7',
    course: 'c1',
    rating: 3,
    comment: 'Good for beginners, could use more advanced topics.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r22',
    user: 'u8',
    course: 'c2',
    rating: 4,
    comment: 'Flexbox and Grid sections were excellent.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r23',
    user: 'u9',
    course: 'c3',
    rating: 5,
    comment: 'Free course with premium quality!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r24',
    user: 'u10',
    course: 'c4',
    rating: 4,
    comment: 'D3.js examples were particularly helpful.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r25',
    user: 'u1',
    course: 'c5',
    rating: 5,
    comment: 'Express.js tutorial was spot on.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r26',
    user: 'u2',
    course: 'c6',
    rating: 4,
    comment: 'Good Docker fundamentals course.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r27',
    user: 'u3',
    course: 'c7',
    rating: 5,
    comment: 'SEO strategies really work!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r28',
    user: 'u4',
    course: 'c8',
    rating: 4,
    comment: 'Both React Native and Flutter covered well.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r29',
    user: 'u5',
    course: 'c9',
    rating: 5,
    comment: 'Automation testing tools were great.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r30',
    user: 'u6',
    course: 'c10',
    rating: 5,
    comment: 'Hands-on ML projects were fantastic.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
];

// Blogs
export const blogs: Blog[] = [
  {
    _id: 'b1',
    title: 'Why Learn JavaScript',
    image: blogImg1.src,
    content: 'Because it runs everywhere.',
    tags: ['js', 'web'],
    author: 'u1',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u2', comment: 'Agreed!', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b2',
    title: 'Best CSS Practices',
    image: blogImg2.src,
    content: 'Use flexbox!',
    tags: ['css'],
    author: 'u2',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u1', comment: 'Useful tips.', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b3',
    title: 'React vs Vue',
    image: blogImg3.src,
    content: 'Choose what fits.',
    tags: ['react', 'vue'],
    author: 'u3',
    createdAt: new Date().toISOString(),
    comments: [],
  },
  {
    _id: 'b4',
    title: 'Node.js for APIs',
    content: 'Express is the go-to.',
    tags: ['node', 'backend'],
    author: 'u4',
    image: blogImg1.src,
    createdAt: new Date().toISOString(),
    comments: [],
  },
  {
    _id: 'b5',
    title: 'Visualizing Data',
    content: 'Charts and dashboards.',
    tags: ['data'],
    author: 'u5',
    image: blogImg2.src,
    createdAt: new Date().toISOString(),
    comments: [],
  },
  {
    _id: 'b6',
    title: 'DevOps Best Practices',
    image: blogImg3.src,
    content: 'Automate everything possible.',
    tags: ['devops', 'automation'],
    author: 'u6',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u8', comment: 'Great insights!', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b7',
    title: 'Digital Marketing Trends 2024',
    image: blogImg1.src,
    content: 'AI-powered marketing is the future.',
    tags: ['marketing', 'ai'],
    author: 'u7',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u10', comment: 'Very insightful.', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b8',
    title: 'Mobile Development Frameworks',
    image: blogImg2.src,
    content: 'React Native vs Flutter comparison.',
    tags: ['mobile', 'react-native', 'flutter'],
    author: 'u8',
    createdAt: new Date().toISOString(),
    comments: [],
  },
  {
    _id: 'b9',
    title: 'Testing Strategies',
    content: 'Unit, integration, and e2e testing.',
    image: blogImg3.src,
    tags: ['testing', 'qa'],
    author: 'u9',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u2', comment: 'Very helpful.', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b10',
    title: 'Machine Learning Applications',
    image: blogImg1.src,
    content: 'Real-world ML use cases.',
    tags: ['ml', 'ai', 'applications'],
    author: 'u10',
    createdAt: new Date().toISOString(),
    comments: [
      { user: 'u3', comment: 'Fascinating examples!', createdAt: new Date().toISOString() },
    ],
  },
];

// Carts
export const carts: Cart[] = [
  { _id: 'cart1', user: 'u1', items: [{ course: 'c1', price: 29.99 }], totalAmount: 29.99 },
  { _id: 'cart2', user: 'u2', items: [{ course: 'c2', price: 39.99 }], totalAmount: 39.99 },
  { _id: 'cart3', user: 'u3', items: [{ course: 'c4', price: 59.99 }], totalAmount: 59.99 },
  { _id: 'cart4', user: 'u4', items: [{ course: 'c5', price: 19.99 }], totalAmount: 19.99 },
  { _id: 'cart5', user: 'u5', items: [], totalAmount: 0 },
  { _id: 'cart6', user: 'u6', items: [{ course: 'c6', price: 34.99 }], totalAmount: 34.99 },
  { _id: 'cart7', user: 'u7', items: [{ course: 'c7', price: 49.99 }], totalAmount: 49.99 },
  {
    _id: 'cart8',
    user: 'u8',
    items: [
      { course: 'c8', price: 0 },
      { course: 'c9', price: 24.99 },
    ],
    totalAmount: 24.99,
  },
  { _id: 'cart9', user: 'u9', items: [{ course: 'c9', price: 24.99 }], totalAmount: 24.99 },
  { _id: 'cart10', user: 'u10', items: [{ course: 'c10', price: 79.99 }], totalAmount: 79.99 },
];

// Orders
export const orders: Order[] = [
  {
    _id: 'o1',
    user: 'u1',
    courses: ['c1', 'c2'],
    totalAmount: 69.98,
    orderedAt: new Date().toISOString(),
  },
  { _id: 'o2', user: 'u2', courses: ['c3'], totalAmount: 0, orderedAt: new Date().toISOString() },
  {
    _id: 'o3',
    user: 'u3',
    courses: ['c4'],
    totalAmount: 59.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o4',
    user: 'u4',
    courses: ['c5'],
    totalAmount: 19.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o5',
    user: 'u5',
    courses: ['c1', 'c3', 'c5'],
    totalAmount: 49.98,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o6',
    user: 'u6',
    courses: ['c6'],
    totalAmount: 34.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o7',
    user: 'u7',
    courses: ['c7', 'c8'],
    totalAmount: 49.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o8',
    user: 'u8',
    courses: ['c8', 'c9'],
    totalAmount: 24.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o9',
    user: 'u9',
    courses: ['c9', 'c1'],
    totalAmount: 54.98,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o10',
    user: 'u10',
    courses: ['c10'],
    totalAmount: 79.99,
    orderedAt: new Date().toISOString(),
  },
];

// Questions
export const questions: Question[] = [
  {
    _id: 'q1',
    user: 'u1',
    course: 'c1',
    question: 'Is this updated for ES6?',
    answer: 'Yes.',
    status: 'read',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q2',
    user: 'u2',
    course: 'c2',
    question: 'Will flexbox be covered?',
    answer: 'Definitely.',
    status: 'important',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q3',
    user: 'u3',
    course: 'c3',
    question: 'Any assignments?',
    answer: 'Yes.',
    status: 'read',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q4',
    user: 'u4',
    course: 'c4',
    question: 'What libraries are used?',
    answer: 'Chart.js and D3.',
    status: 'archived',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q5',
    user: 'u5',
    course: 'c5',
    question: 'Do I need Node installed?',
    answer: 'Yes.',
    status: 'unread',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q6',
    user: 'u6',
    course: 'c6',
    question: 'What Docker version is required?',
    answer: 'Docker 20.10 or higher.',
    status: 'read',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q7',
    user: 'u7',
    course: 'c7',
    question: 'Are there practical marketing exercises?',
    answer: 'Yes, lots of hands-on activities.',
    status: 'important',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q8',
    user: 'u8',
    course: 'c8',
    question: 'Which mobile platforms are covered?',
    answer: 'Both iOS and Android.',
    status: 'read',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q9',
    user: 'u9',
    course: 'c9',
    question: 'What testing tools are taught?',
    answer: 'Jest, Cypress, and Selenium.',
    status: 'unread',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q10',
    user: 'u10',
    course: 'c10',
    question: 'Is Python knowledge required?',
    answer: 'Basic Python knowledge is helpful.',
    status: 'archived',
    createdAt: new Date().toISOString(),
  },
];

// Instructors
export const instructors: Instructor[] = [
  {
    _id: 'i1',
    user: 'u2',
    expertise: ['JavaScript', 'Node.js'],
    isTop: true,
  },
  {
    _id: 'i2',
    user: 'u3',
    expertise: ['Data Science', 'Python'],
    isTop: false,
  },
  {
    _id: 'i3',
    user: 'u5',
    expertise: ['React', 'Frontend'],
    isTop: true,
  },
  {
    _id: 'i4',
    user: 'u4',
    expertise: ['Project Management', 'Agile'],
    isTop: false,
  },
  {
    _id: 'i5',
    user: 'u1',
    expertise: ['UX', 'Design'],
    isTop: false,
  },
  {
    _id: 'i6',
    user: 'u6',
    expertise: ['DevOps', 'Docker', 'AWS'],
    isTop: true,
  },
  {
    _id: 'i7',
    user: 'u7',
    expertise: ['Digital Marketing', 'SEO', 'Social Media'],
    isTop: false,
  },
  {
    _id: 'i8',
    user: 'u8',
    expertise: ['React Native', 'Flutter', 'Mobile UI'],
    isTop: true,
  },
  {
    _id: 'i9',
    user: 'u9',
    expertise: ['Test Automation', 'Quality Assurance'],
    isTop: false,
  },
  {
    _id: 'i10',
    user: 'u10',
    expertise: ['Machine Learning', 'Python', 'Data Science'],
    isTop: true,
  },
];

// Subscribers
export const subscribers: Subscriber[] = [
  { _id: 's1', email: 'alice@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's2', email: 'bob@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's3', email: 'cathy@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's4', email: 'david@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's5', email: 'eva@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's6', email: 'frank@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's7', email: 'grace@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's8', email: 'henry@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's9', email: 'ivy@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's10', email: 'jack@newsletter.com', subscribedAt: new Date().toISOString() },
];
