import {
  User,
  Course,
  Enrolment,
  Review,
  Blog,
  Cart,
  Order,
  Question,
  Instructor,
  Subscriber,
} from './mockDataTypes';

// Users
export const users: User[] = [
  {
    _id: 'u1',
    name: 'Alice Johnson',
    username: 'alicej',
    email: 'alice@example.com',
    phone: '01710000001',
    password: 'hashed123',
    occupation: 'Designer',
    bio: 'UX/UI Designer with 5 years experience',
    socialLinks: ['https://linkedin.com/alicej'],
    image: 'https://source.unsplash.com/featured/300x300?face,woman',
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: ['c2'],
  },
  {
    _id: 'u2',
    name: 'Bob Smith',
    username: 'bobsmith',
    email: 'bob@example.com',
    phone: '01710000002',
    password: 'hashed456',
    occupation: 'Backend Developer',
    bio: 'Node.js developer',
    socialLinks: ['https://github.com/bobsmith'],
    image: 'https://source.unsplash.com/featured/300x300?face,man',
    role: 'instructor',
    registeredAt: new Date().toISOString(),
    wishlist: ['c1'],
  },
  {
    _id: 'u3',
    name: 'Cathy Lee',
    username: 'cathyl',
    email: 'cathy@example.com',
    phone: '01710000003',
    password: 'hashed789',
    occupation: 'Data Analyst',
    bio: 'Works with data at a fintech company',
    socialLinks: ['https://twitter.com/cathyl'],
    image: 'https://source.unsplash.com/featured/300x300?face,woman,smile',
    role: 'admin',
    registeredAt: new Date().toISOString(),
    wishlist: ['c4'],
  },
  {
    _id: 'u4',
    name: 'David Kim',
    username: 'davidk',
    email: 'david@example.com',
    phone: '01710000004',
    password: 'hashed101',
    occupation: 'Product Manager',
    bio: 'Manages software projects',
    socialLinks: [],
    image: 'https://source.unsplash.com/featured/300x300?face,man,glasses',
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: [],
  },
  {
    _id: 'u5',
    name: 'Eva Green',
    username: 'evagreen',
    email: 'eva@example.com',
    phone: '01710000005',
    password: 'hashed102',
    occupation: 'Full Stack Developer',
    bio: 'Freelancer',
    socialLinks: ['https://github.com/evagreen'],
    image: 'https://source.unsplash.com/featured/300x300?face,woman,developer',
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: ['c5'],
  },
  {
    _id: 'u6',
    name: 'Frank Miller',
    username: 'frankm',
    email: 'frank@example.com',
    phone: '01710000006',
    password: 'hashed103',
    occupation: 'DevOps Engineer',
    bio: 'Cloud infrastructure specialist',
    socialLinks: ['https://linkedin.com/frankm'],
    image: 'https://source.unsplash.com/featured/300x300?face,man,beard',
    role: 'instructor',
    registeredAt: new Date().toISOString(),
    wishlist: ['c6', 'c7'],
  },
  {
    _id: 'u7',
    name: 'Grace Wilson',
    username: 'gracew',
    email: 'grace@example.com',
    phone: '01710000007',
    password: 'hashed104',
    occupation: 'Marketing Manager',
    bio: 'Digital marketing enthusiast',
    socialLinks: ['https://twitter.com/gracew', 'https://instagram.com/gracew'],
    image: 'https://source.unsplash.com/featured/300x300?face,woman,professional',
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: ['c8'],
  },
  {
    _id: 'u8',
    name: 'Henry Brown',
    username: 'henryb',
    email: 'henry@example.com',
    phone: '01710000008',
    password: 'hashed105',
    occupation: 'Mobile Developer',
    bio: 'React Native and Flutter developer',
    socialLinks: ['https://github.com/henryb'],
    image: 'https://source.unsplash.com/featured/300x300?face,man,young',
    role: 'instructor',
    registeredAt: new Date().toISOString(),
    wishlist: ['c9'],
  },
  {
    _id: 'u9',
    name: 'Ivy Chen',
    username: 'ivyc',
    email: 'ivy@example.com',
    phone: '01710000009',
    password: 'hashed106',
    occupation: 'QA Engineer',
    bio: 'Automation testing specialist',
    socialLinks: ['https://linkedin.com/ivyc'],
    image: 'https://source.unsplash.com/featured/300x300?face,woman,asian',
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: ['c10'],
  },
  {
    _id: 'u10',
    name: 'Jack Davis',
    username: 'jackd',
    email: 'jack@example.com',
    phone: '01710000010',
    password: 'hashed107',
    occupation: 'AI Engineer',
    bio: 'Machine learning and AI researcher',
    socialLinks: ['https://github.com/jackd', 'https://medium.com/@jackd'],
    image: 'https://source.unsplash.com/featured/300x300?face,man,scientist',
    role: 'instructor',
    registeredAt: new Date().toISOString(),
    wishlist: ['c1', 'c3'],
  },
];

// Courses
export const courses: Course[] = [
  {
    _id: 'c1',
    title: 'Intro to JavaScript',
    category: 'Programming',
    price: 29.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?javascript,code',
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: [
      'https://www.w3schools.com/html/mov_bbb.mp4',
      'https://www.w3schools.com/html/movie.mp4',
    ],
    featured: true,
    instructor: 'u2',
    reviews: ['r1', 'r11', 'r21'],
    enrolments: ['e1', 'e11', 'e21'],
  },
  {
    _id: 'c2',
    title: 'Advanced CSS',
    category: 'Design',
    price: 39.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?css,design',
    demoVideo: 'https://www.w3schools.com/html/movie.mp4',
    lessons: ['https://www.w3schools.com/html/movie.mp4'],
    featured: false,
    instructor: 'u2',
    reviews: ['r2', 'r12', 'r22'],
    enrolments: ['e2', 'e12', 'e22'],
  },
  {
    _id: 'c3',
    title: 'React Basics',
    category: 'Web Development',
    price: 0,
    isFree: true,
    thumbnail: 'https://source.unsplash.com/featured/400x300?react,frontend',
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: ['https://www.w3schools.com/html/mov_bbb.mp4'],
    featured: true,
    instructor: 'u5',
    reviews: ['r3', 'r13', 'r23'],
    enrolments: ['e3', 'e13', 'e23'],
  },
  {
    _id: 'c4',
    title: 'Data Visualization',
    category: 'Data Science',
    price: 59.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?data,charts',
    demoVideo: 'https://www.w3schools.com/html/movie.mp4',
    lessons: ['https://www.w3schools.com/html/movie.mp4'],
    featured: false,
    instructor: 'u3',
    reviews: ['r4', 'r14', 'r24'],
    enrolments: ['e4', 'e14', 'e24'],
  },
  {
    _id: 'c5',
    title: 'Node.js Crash Course',
    category: 'Backend',
    price: 19.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?nodejs,backend',
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: ['https://www.w3schools.com/html/mov_bbb.mp4'],
    featured: true,
    instructor: 'u2',
    reviews: ['r5', 'r15', 'r25'],
    enrolments: ['e5', 'e15', 'e25'],
  },
  {
    _id: 'c6',
    title: 'Docker for Beginners',
    category: 'DevOps',
    price: 34.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?docker,containers',
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: [
      'https://www.w3schools.com/html/mov_bbb.mp4',
      'https://www.w3schools.com/html/movie.mp4',
    ],
    featured: true,
    instructor: 'u6',
    reviews: ['r6', 'r16', 'r26'],
    enrolments: ['e6', 'e16', 'e26'],
  },
  {
    _id: 'c7',
    title: 'Digital Marketing Essentials',
    category: 'Marketing',
    price: 49.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?marketing,digital',
    demoVideo: 'https://www.w3schools.com/html/movie.mp4',
    lessons: ['https://www.w3schools.com/html/movie.mp4'],
    featured: false,
    instructor: 'u7',
    reviews: ['r7', 'r17', 'r27'],
    enrolments: ['e7', 'e17', 'e27'],
  },
  {
    _id: 'c8',
    title: 'Mobile App Development',
    category: 'Mobile',
    price: 0,
    isFree: true,
    thumbnail: 'https://source.unsplash.com/featured/400x300?mobile,app',
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: ['https://www.w3schools.com/html/mov_bbb.mp4'],
    featured: true,
    instructor: 'u8',
    reviews: ['r8', 'r18', 'r28'],
    enrolments: ['e8', 'e18', 'e28'],
  },
  {
    _id: 'c9',
    title: 'Software Testing Fundamentals',
    category: 'Testing',
    price: 24.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?testing,qa',
    demoVideo: 'https://www.w3schools.com/html/movie.mp4',
    lessons: ['https://www.w3schools.com/html/movie.mp4'],
    featured: false,
    instructor: 'u9',
    reviews: ['r9', 'r19', 'r29'],
    enrolments: ['e9', 'e19', 'e29'],
  },
  {
    _id: 'c10',
    title: 'Machine Learning with Python',
    category: 'AI/ML',
    price: 79.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?machine,learning',
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: [
      'https://www.w3schools.com/html/mov_bbb.mp4',
      'https://www.w3schools.com/html/movie.mp4',
    ],
    featured: true,
    instructor: 'u10',
    reviews: ['r10', 'r20', 'r30'],
    enrolments: ['e10', 'e20', 'e30'],
  },
];

// Enrolments
export const enrolments: Enrolment[] = [
  { _id: 'e1', user: 'u1', course: 'c1', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e2',
    user: 'u2',
    course: 'c2',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e3', user: 'u3', course: 'c3', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e4',
    user: 'u4',
    course: 'c4',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e5', user: 'u5', course: 'c5', status: 'active', enrolledAt: new Date().toISOString() },
  { _id: 'e6', user: 'u6', course: 'c6', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e7',
    user: 'u7',
    course: 'c7',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e8', user: 'u8', course: 'c8', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e9',
    user: 'u9',
    course: 'c9',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  {
    _id: 'e10',
    user: 'u10',
    course: 'c10',
    status: 'active',
    enrolledAt: new Date().toISOString(),
  },
  // Additional enrollments for multiple per course
  {
    _id: 'e11',
    user: 'u4',
    course: 'c1',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e12', user: 'u5', course: 'c2', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e13',
    user: 'u6',
    course: 'c3',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e14', user: 'u7', course: 'c4', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e15',
    user: 'u8',
    course: 'c5',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e16', user: 'u9', course: 'c6', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e17',
    user: 'u10',
    course: 'c7',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e18', user: 'u1', course: 'c8', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e19',
    user: 'u2',
    course: 'c9',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e20', user: 'u3', course: 'c10', status: 'active', enrolledAt: new Date().toISOString() },
  // Third enrollment for each course
  { _id: 'e21', user: 'u7', course: 'c1', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e22',
    user: 'u8',
    course: 'c2',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e23', user: 'u9', course: 'c3', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e24',
    user: 'u10',
    course: 'c4',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e25', user: 'u1', course: 'c5', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e26',
    user: 'u2',
    course: 'c6',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e27', user: 'u3', course: 'c7', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e28',
    user: 'u4',
    course: 'c8',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e29', user: 'u5', course: 'c9', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e30',
    user: 'u6',
    course: 'c10',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
];

// Reviews
export const reviews: Review[] = [
  {
    _id: 'r1',
    user: 'u1',
    course: 'c1',
    rating: 5,
    comment: 'Loved it!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r2',
    user: 'u2',
    course: 'c2',
    rating: 4,
    comment: 'Great explanations.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r3',
    user: 'u3',
    course: 'c3',
    rating: 3,
    comment: 'Good but basic.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r4',
    user: 'u4',
    course: 'c4',
    rating: 4,
    comment: 'Well structured.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r5',
    user: 'u5',
    course: 'c5',
    rating: 5,
    comment: 'Perfect for beginners!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r6',
    user: 'u6',
    course: 'c6',
    rating: 4,
    comment: 'Docker made easy!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r7',
    user: 'u7',
    course: 'c7',
    rating: 5,
    comment: 'Comprehensive marketing guide.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r8',
    user: 'u8',
    course: 'c8',
    rating: 4,
    comment: 'Great for mobile development.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r9',
    user: 'u9',
    course: 'c9',
    rating: 3,
    comment: 'Solid foundation in testing.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r10',
    user: 'u10',
    course: 'c10',
    rating: 5,
    comment: 'Excellent ML course!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  // Additional reviews for multiple per course
  {
    _id: 'r11',
    user: 'u4',
    course: 'c1',
    rating: 4,
    comment: 'Clear and concise JavaScript tutorial.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r12',
    user: 'u5',
    course: 'c2',
    rating: 5,
    comment: 'CSS animations were amazing!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r13',
    user: 'u6',
    course: 'c3',
    rating: 4,
    comment: 'Good introduction to React.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r14',
    user: 'u7',
    course: 'c4',
    rating: 5,
    comment: 'Beautiful visualizations taught here.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r15',
    user: 'u8',
    course: 'c5',
    rating: 4,
    comment: 'Solid Node.js fundamentals.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r16',
    user: 'u9',
    course: 'c6',
    rating: 5,
    comment: 'Container concepts well explained.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r17',
    user: 'u10',
    course: 'c7',
    rating: 4,
    comment: 'Practical marketing strategies.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r18',
    user: 'u1',
    course: 'c8',
    rating: 5,
    comment: 'Mobile development made simple.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r19',
    user: 'u2',
    course: 'c9',
    rating: 4,
    comment: 'Comprehensive testing coverage.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r20',
    user: 'u3',
    course: 'c10',
    rating: 5,
    comment: "Best ML course I've taken!",
    featured: true,
    createdAt: new Date().toISOString(),
  },
  // Third review for each course
  {
    _id: 'r21',
    user: 'u7',
    course: 'c1',
    rating: 3,
    comment: 'Good for beginners, could use more advanced topics.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r22',
    user: 'u8',
    course: 'c2',
    rating: 4,
    comment: 'Flexbox and Grid sections were excellent.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r23',
    user: 'u9',
    course: 'c3',
    rating: 5,
    comment: 'Free course with premium quality!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r24',
    user: 'u10',
    course: 'c4',
    rating: 4,
    comment: 'D3.js examples were particularly helpful.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r25',
    user: 'u1',
    course: 'c5',
    rating: 5,
    comment: 'Express.js tutorial was spot on.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r26',
    user: 'u2',
    course: 'c6',
    rating: 4,
    comment: 'Good Docker fundamentals course.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r27',
    user: 'u3',
    course: 'c7',
    rating: 5,
    comment: 'SEO strategies really work!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r28',
    user: 'u4',
    course: 'c8',
    rating: 4,
    comment: 'Both React Native and Flutter covered well.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r29',
    user: 'u5',
    course: 'c9',
    rating: 5,
    comment: 'Automation testing tools were great.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r30',
    user: 'u6',
    course: 'c10',
    rating: 5,
    comment: 'Hands-on ML projects were fantastic.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
];

// Blogs
export const blogs: Blog[] = [
  {
    _id: 'b1',
    title: 'Why Learn JavaScript',
    content: 'Because it runs everywhere.',
    tags: ['js', 'web'],
    author: 'u1',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u2', comment: 'Agreed!', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b2',
    title: 'Best CSS Practices',
    content: 'Use flexbox!',
    tags: ['css'],
    author: 'u2',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u1', comment: 'Useful tips.', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b3',
    title: 'React vs Vue',
    content: 'Choose what fits.',
    tags: ['react', 'vue'],
    author: 'u3',
    createdAt: new Date().toISOString(),
    comments: [],
  },
  {
    _id: 'b4',
    title: 'Node.js for APIs',
    content: 'Express is the go-to.',
    tags: ['node', 'backend'],
    author: 'u4',
    createdAt: new Date().toISOString(),
    comments: [],
  },
  {
    _id: 'b5',
    title: 'Visualizing Data',
    content: 'Charts and dashboards.',
    tags: ['data'],
    author: 'u5',
    createdAt: new Date().toISOString(),
    comments: [],
  },
  {
    _id: 'b6',
    title: 'DevOps Best Practices',
    content: 'Automate everything possible.',
    tags: ['devops', 'automation'],
    author: 'u6',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u8', comment: 'Great insights!', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b7',
    title: 'Digital Marketing Trends 2024',
    content: 'AI-powered marketing is the future.',
    tags: ['marketing', 'ai'],
    author: 'u7',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u10', comment: 'Very insightful.', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b8',
    title: 'Mobile Development Frameworks',
    content: 'React Native vs Flutter comparison.',
    tags: ['mobile', 'react-native', 'flutter'],
    author: 'u8',
    createdAt: new Date().toISOString(),
    comments: [],
  },
  {
    _id: 'b9',
    title: 'Testing Strategies',
    content: 'Unit, integration, and e2e testing.',
    tags: ['testing', 'qa'],
    author: 'u9',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u2', comment: 'Very helpful.', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b10',
    title: 'Machine Learning Applications',
    content: 'Real-world ML use cases.',
    tags: ['ml', 'ai', 'applications'],
    author: 'u10',
    createdAt: new Date().toISOString(),
    comments: [
      { user: 'u3', comment: 'Fascinating examples!', createdAt: new Date().toISOString() },
    ],
  },
];

// Carts
export const carts: Cart[] = [
  { _id: 'cart1', user: 'u1', items: [{ course: 'c1', price: 29.99 }], totalAmount: 29.99 },
  { _id: 'cart2', user: 'u2', items: [{ course: 'c2', price: 39.99 }], totalAmount: 39.99 },
  { _id: 'cart3', user: 'u3', items: [{ course: 'c4', price: 59.99 }], totalAmount: 59.99 },
  { _id: 'cart4', user: 'u4', items: [{ course: 'c5', price: 19.99 }], totalAmount: 19.99 },
  { _id: 'cart5', user: 'u5', items: [], totalAmount: 0 },
  { _id: 'cart6', user: 'u6', items: [{ course: 'c6', price: 34.99 }], totalAmount: 34.99 },
  { _id: 'cart7', user: 'u7', items: [{ course: 'c7', price: 49.99 }], totalAmount: 49.99 },
  {
    _id: 'cart8',
    user: 'u8',
    items: [
      { course: 'c8', price: 0 },
      { course: 'c9', price: 24.99 },
    ],
    totalAmount: 24.99,
  },
  { _id: 'cart9', user: 'u9', items: [{ course: 'c9', price: 24.99 }], totalAmount: 24.99 },
  { _id: 'cart10', user: 'u10', items: [{ course: 'c10', price: 79.99 }], totalAmount: 79.99 },
];

// Orders
export const orders: Order[] = [
  {
    _id: 'o1',
    user: 'u1',
    courses: ['c1', 'c2'],
    totalAmount: 69.98,
    orderedAt: new Date().toISOString(),
  },
  { _id: 'o2', user: 'u2', courses: ['c3'], totalAmount: 0, orderedAt: new Date().toISOString() },
  {
    _id: 'o3',
    user: 'u3',
    courses: ['c4'],
    totalAmount: 59.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o4',
    user: 'u4',
    courses: ['c5'],
    totalAmount: 19.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o5',
    user: 'u5',
    courses: ['c1', 'c3', 'c5'],
    totalAmount: 49.98,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o6',
    user: 'u6',
    courses: ['c6'],
    totalAmount: 34.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o7',
    user: 'u7',
    courses: ['c7', 'c8'],
    totalAmount: 49.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o8',
    user: 'u8',
    courses: ['c8', 'c9'],
    totalAmount: 24.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o9',
    user: 'u9',
    courses: ['c9', 'c1'],
    totalAmount: 54.98,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o10',
    user: 'u10',
    courses: ['c10'],
    totalAmount: 79.99,
    orderedAt: new Date().toISOString(),
  },
];

// Questions
export const questions: Question[] = [
  {
    _id: 'q1',
    user: 'u1',
    course: 'c1',
    question: 'Is this updated for ES6?',
    answer: 'Yes.',
    status: 'read',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q2',
    user: 'u2',
    course: 'c2',
    question: 'Will flexbox be covered?',
    answer: 'Definitely.',
    status: 'important',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q3',
    user: 'u3',
    course: 'c3',
    question: 'Any assignments?',
    answer: 'Yes.',
    status: 'read',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q4',
    user: 'u4',
    course: 'c4',
    question: 'What libraries are used?',
    answer: 'Chart.js and D3.',
    status: 'archived',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q5',
    user: 'u5',
    course: 'c5',
    question: 'Do I need Node installed?',
    answer: 'Yes.',
    status: 'unread',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q6',
    user: 'u6',
    course: 'c6',
    question: 'What Docker version is required?',
    answer: 'Docker 20.10 or higher.',
    status: 'read',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q7',
    user: 'u7',
    course: 'c7',
    question: 'Are there practical marketing exercises?',
    answer: 'Yes, lots of hands-on activities.',
    status: 'important',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q8',
    user: 'u8',
    course: 'c8',
    question: 'Which mobile platforms are covered?',
    answer: 'Both iOS and Android.',
    status: 'read',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q9',
    user: 'u9',
    course: 'c9',
    question: 'What testing tools are taught?',
    answer: 'Jest, Cypress, and Selenium.',
    status: 'unread',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q10',
    user: 'u10',
    course: 'c10',
    question: 'Is Python knowledge required?',
    answer: 'Basic Python knowledge is helpful.',
    status: 'archived',
    createdAt: new Date().toISOString(),
  },
];

// Instructors
export const instructors: Instructor[] = [
  {
    _id: 'i1',
    user: 'u2',
    image: 'https://source.unsplash.com/featured/300x300?teacher,man',
    expertise: ['JavaScript', 'Node.js'],
    isTop: true,
  },
  {
    _id: 'i2',
    user: 'u3',
    image: 'https://source.unsplash.com/featured/300x300?teacher,woman',
    expertise: ['Data Science', 'Python'],
    isTop: false,
  },
  {
    _id: 'i3',
    user: 'u5',
    image: 'https://source.unsplash.com/featured/300x300?instructor,frontend',
    expertise: ['React', 'Frontend'],
    isTop: true,
  },
  {
    _id: 'i4',
    user: 'u4',
    image: 'https://source.unsplash.com/featured/300x300?project,manager',
    expertise: ['Project Management', 'Agile'],
    isTop: false,
  },
  {
    _id: 'i5',
    user: 'u1',
    image: 'https://source.unsplash.com/featured/300x300?ux,designer',
    expertise: ['UX', 'Design'],
    isTop: false,
  },
  {
    _id: 'i6',
    user: 'u6',
    image: 'https://source.unsplash.com/featured/300x300?devops,engineer',
    expertise: ['DevOps', 'Docker', 'AWS'],
    isTop: true,
  },
  {
    _id: 'i7',
    user: 'u7',
    image: 'https://source.unsplash.com/featured/300x300?marketing,professional',
    expertise: ['Digital Marketing', 'SEO', 'Social Media'],
    isTop: false,
  },
  {
    _id: 'i8',
    user: 'u8',
    image: 'https://source.unsplash.com/featured/300x300?mobile,developer',
    expertise: ['React Native', 'Flutter', 'Mobile UI'],
    isTop: true,
  },
  {
    _id: 'i9',
    user: 'u9',
    image: 'https://source.unsplash.com/featured/300x300?qa,tester',
    expertise: ['Test Automation', 'Quality Assurance'],
    isTop: false,
  },
  {
    _id: 'i10',
    user: 'u10',
    image: 'https://source.unsplash.com/featured/300x300?ai,scientist',
    expertise: ['Machine Learning', 'Python', 'Data Science'],
    isTop: true,
  },
];

// Subscribers
export const subscribers: Subscriber[] = [
  { _id: 's1', email: 'alice@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's2', email: 'bob@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's3', email: 'cathy@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's4', email: 'david@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's5', email: 'eva@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's6', email: 'frank@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's7', email: 'grace@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's8', email: 'henry@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's9', email: 'ivy@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's10', email: 'jack@newsletter.com', subscribedAt: new Date().toISOString() },
];
