import {
  User,
  Course,
  Enrolment,
  Review,
  Blog,
  Cart,
  Order,
  Question,
  Instructor,
  Subscriber,
} from './mockDataTypes';

// Users
export const users: User[] = [
  {
    _id: 'u1',
    name: 'Alice Johnson',
    username: 'alicej',
    email: 'alice@example.com',
    phone: '01710000001',
    password: 'hashed123',
    occupation: 'Designer',
    bio: 'UX/UI Designer with 5 years experience',
    socialLinks: ['https://linkedin.com/alicej'],
    image: 'https://source.unsplash.com/featured/300x300?face,woman',
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: ['c2'],
  },
  {
    _id: 'u2',
    name: 'Bob Smith',
    username: 'bobsmith',
    email: 'bob@example.com',
    phone: '01710000002',
    password: 'hashed456',
    occupation: 'Backend Developer',
    bio: 'Node.js developer',
    socialLinks: ['https://github.com/bobsmith'],
    image: 'https://source.unsplash.com/featured/300x300?face,man',
    role: 'instructor',
    registeredAt: new Date().toISOString(),
    wishlist: ['c1'],
  },
  {
    _id: 'u3',
    name: 'Cathy Lee',
    username: 'cathyl',
    email: 'cathy@example.com',
    phone: '01710000003',
    password: 'hashed789',
    occupation: 'Data Analyst',
    bio: 'Works with data at a fintech company',
    socialLinks: ['https://twitter.com/cathyl'],
    image: 'https://source.unsplash.com/featured/300x300?face,woman,smile',
    role: 'admin',
    registeredAt: new Date().toISOString(),
    wishlist: ['c4'],
  },
  {
    _id: 'u4',
    name: 'David Kim',
    username: 'davidk',
    email: 'david@example.com',
    phone: '01710000004',
    password: 'hashed101',
    occupation: 'Product Manager',
    bio: 'Manages software projects',
    socialLinks: [],
    image: 'https://source.unsplash.com/featured/300x300?face,man,glasses',
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: [],
  },
  {
    _id: 'u5',
    name: 'Eva Green',
    username: 'evagreen',
    email: 'eva@example.com',
    phone: '01710000005',
    password: 'hashed102',
    occupation: 'Full Stack Developer',
    bio: 'Freelancer',
    socialLinks: ['https://github.com/evagreen'],
    image: 'https://source.unsplash.com/featured/300x300?face,woman,developer',
    role: 'user',
    registeredAt: new Date().toISOString(),
    wishlist: ['c5'],
  },
];

// Courses
export const courses: Course[] = [
  {
    _id: 'c1',
    title: 'Intro to JavaScript',
    category: 'Programming',
    price: 29.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?javascript,code',
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: [
      'https://www.w3schools.com/html/mov_bbb.mp4',
      'https://www.w3schools.com/html/movie.mp4',
    ],
    featured: true,
    instructor: 'u2',
    reviews: ['r1'],
    enrolments: ['e1'],
  },
  {
    _id: 'c2',
    title: 'Advanced CSS',
    category: 'Design',
    price: 39.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?css,design',
    demoVideo: 'https://www.w3schools.com/html/movie.mp4',
    lessons: ['https://www.w3schools.com/html/movie.mp4'],
    featured: false,
    instructor: 'u2',
    reviews: ['r2'],
    enrolments: ['e2'],
  },
  {
    _id: 'c3',
    title: 'React Basics',
    category: 'Web Development',
    price: 0,
    isFree: true,
    thumbnail: 'https://source.unsplash.com/featured/400x300?react,frontend',
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: ['https://www.w3schools.com/html/mov_bbb.mp4'],
    featured: true,
    instructor: 'u5',
    reviews: ['r3'],
    enrolments: ['e3'],
  },
  {
    _id: 'c4',
    title: 'Data Visualization',
    category: 'Data Science',
    price: 59.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?data,charts',
    demoVideo: 'https://www.w3schools.com/html/movie.mp4',
    lessons: ['https://www.w3schools.com/html/movie.mp4'],
    featured: false,
    instructor: 'u3',
    reviews: [],
    enrolments: ['e5'],
  },
  {
    _id: 'c5',
    title: 'Node.js Crash Course',
    category: 'Backend',
    price: 19.99,
    isFree: false,
    thumbnail: 'https://source.unsplash.com/featured/400x300?nodejs,backend',
    demoVideo: 'https://www.w3schools.com/html/mov_bbb.mp4',
    lessons: ['https://www.w3schools.com/html/mov_bbb.mp4'],
    featured: true,
    instructor: 'u2',
    reviews: ['r4', 'r5'],
    enrolments: ['e1'],
  },
];

// Enrolments
export const enrolments: Enrolment[] = [
  { _id: 'e1', user: 'u1', course: 'c1', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e2',
    user: 'u2',
    course: 'c2',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e3', user: 'u3', course: 'c3', status: 'active', enrolledAt: new Date().toISOString() },
  {
    _id: 'e4',
    user: 'u4',
    course: 'c1',
    status: 'completed',
    enrolledAt: new Date().toISOString(),
  },
  { _id: 'e5', user: 'u5', course: 'c4', status: 'active', enrolledAt: new Date().toISOString() },
];

// Reviews
export const reviews: Review[] = [
  {
    _id: 'r1',
    user: 'u1',
    course: 'c1',
    rating: 5,
    comment: 'Loved it!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r2',
    user: 'u2',
    course: 'c2',
    rating: 4,
    comment: 'Great explanations.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r3',
    user: 'u3',
    course: 'c3',
    rating: 3,
    comment: 'Good but basic.',
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r4',
    user: 'u4',
    course: 'c5',
    rating: 4,
    comment: 'Well structured.',
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'r5',
    user: 'u5',
    course: 'c5',
    rating: 5,
    comment: 'Perfect for beginners!',
    featured: true,
    createdAt: new Date().toISOString(),
  },
];

// Blogs
export const blogs: Blog[] = [
  {
    _id: 'b1',
    title: 'Why Learn JavaScript',
    content: 'Because it runs everywhere.',
    tags: ['js', 'web'],
    author: 'u1',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u2', comment: 'Agreed!', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b2',
    title: 'Best CSS Practices',
    content: 'Use flexbox!',
    tags: ['css'],
    author: 'u2',
    createdAt: new Date().toISOString(),
    comments: [{ user: 'u1', comment: 'Useful tips.', createdAt: new Date().toISOString() }],
  },
  {
    _id: 'b3',
    title: 'React vs Vue',
    content: 'Choose what fits.',
    tags: ['react', 'vue'],
    author: 'u3',
    createdAt: new Date().toISOString(),
    comments: [],
  },
  {
    _id: 'b4',
    title: 'Node.js for APIs',
    content: 'Express is the go-to.',
    tags: ['node', 'backend'],
    author: 'u4',
    createdAt: new Date().toISOString(),
    comments: [],
  },
  {
    _id: 'b5',
    title: 'Visualizing Data',
    content: 'Charts and dashboards.',
    tags: ['data'],
    author: 'u5',
    createdAt: new Date().toISOString(),
    comments: [],
  },
];

// Carts
export const carts: Cart[] = [
  { _id: 'cart1', user: 'u1', items: [{ course: 'c1', price: 29.99 }], totalAmount: 29.99 },
  { _id: 'cart2', user: 'u2', items: [{ course: 'c2', price: 39.99 }], totalAmount: 39.99 },
  { _id: 'cart3', user: 'u3', items: [{ course: 'c4', price: 59.99 }], totalAmount: 59.99 },
  { _id: 'cart4', user: 'u4', items: [{ course: 'c5', price: 19.99 }], totalAmount: 19.99 },
  { _id: 'cart5', user: 'u5', items: [], totalAmount: 0 },
];

// Orders
export const orders: Order[] = [
  {
    _id: 'o1',
    user: 'u1',
    courses: ['c1', 'c2'],
    totalAmount: 69.98,
    orderedAt: new Date().toISOString(),
  },
  { _id: 'o2', user: 'u2', courses: ['c3'], totalAmount: 0, orderedAt: new Date().toISOString() },
  {
    _id: 'o3',
    user: 'u3',
    courses: ['c4'],
    totalAmount: 59.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o4',
    user: 'u4',
    courses: ['c5'],
    totalAmount: 19.99,
    orderedAt: new Date().toISOString(),
  },
  {
    _id: 'o5',
    user: 'u5',
    courses: ['c1', 'c3', 'c5'],
    totalAmount: 49.98,
    orderedAt: new Date().toISOString(),
  },
];

// Questions
export const questions: Question[] = [
  {
    _id: 'q1',
    user: 'u1',
    course: 'c1',
    question: 'Is this updated for ES6?',
    answer: 'Yes.',
    status: 'read',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q2',
    user: 'u2',
    course: 'c2',
    question: 'Will flexbox be covered?',
    answer: 'Definitely.',
    status: 'important',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q3',
    user: 'u3',
    course: 'c3',
    question: 'Any assignments?',
    answer: 'Yes.',
    status: 'read',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q4',
    user: 'u4',
    course: 'c4',
    question: 'What libraries are used?',
    answer: 'Chart.js and D3.',
    status: 'archived',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'q5',
    user: 'u5',
    course: 'c5',
    question: 'Do I need Node installed?',
    answer: 'Yes.',
    status: 'unread',
    createdAt: new Date().toISOString(),
  },
];

// Instructors
export const instructors: Instructor[] = [
  {
    _id: 'i1',
    user: 'u2',
    image: 'https://source.unsplash.com/featured/300x300?teacher,man',
    expertise: ['JavaScript', 'Node.js'],
    isTop: true,
  },
  {
    _id: 'i2',
    user: 'u3',
    image: 'https://source.unsplash.com/featured/300x300?teacher,woman',
    expertise: ['Data Science', 'Python'],
    isTop: false,
  },
  {
    _id: 'i3',
    user: 'u5',
    image: 'https://source.unsplash.com/featured/300x300?instructor,frontend',
    expertise: ['React', 'Frontend'],
    isTop: true,
  },
  {
    _id: 'i4',
    user: 'u4',
    image: 'https://source.unsplash.com/featured/300x300?project,manager',
    expertise: ['Project Management', 'Agile'],
    isTop: false,
  },
  {
    _id: 'i5',
    user: 'u1',
    image: 'https://source.unsplash.com/featured/300x300?ux,designer',
    expertise: ['UX', 'Design'],
    isTop: false,
  },
];

// Subscribers
export const subscribers: Subscriber[] = [
  { _id: 's1', email: 'alice@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's2', email: 'bob@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's3', email: 'cathy@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's4', email: 'david@newsletter.com', subscribedAt: new Date().toISOString() },
  { _id: 's5', email: 'eva@newsletter.com', subscribedAt: new Date().toISOString() },
];
