name: Deploy to VPS

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 85.31.225.81
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/techsprout
            git fetch --all
            git reset --hard origin/main
            pnpm install
            pnpm build
            pm2 restart techsprout || pm2 start techsprout
            pm2 save
